FROM ghcr.io/othermythos/asset-builder-image:latest

RUN apt-get update && apt-get install -y \
    scons \
    libglfw3-dev \
    libgtk-3-dev \
    unzip \
    cmake \
    python3-numpy

#Build it here to avoid any discrepancies between x86 and arm.
RUN mkdir /goxelBuild
RUN wget https://github.com/OtherMythos/goxel/archive/refs/heads/master.zip -P /goxelBuild/
RUN cd /goxelBuild/ && unzip *.zip
RUN cd /goxelBuild/goxel-master && make release && make install

#Build the VoxelConverterTool
RUN mkdir /VoxelConverterTool
#To skip copying a user's local build
COPY VoxelConverterTool/src /VoxelConverterTool/src
COPY VoxelConverterTool/CMakeLists.txt /VoxelConverterTool/CMakeLists.txt
RUN cd /VoxelConverterTool && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make && make install
RUN VoxelConverterTool

COPY voxelConverter.py /builder/voxelConverter.py
COPY AssetModuleGox.py /scripts/assetPipeline/assetModules/AssetModuleGox.py