
::EnumDef.addToEnum("ItemId", @"

    HEALTH_POTION,
    LARGE_HEALTH_POTION,

    SIMPLE_SWORD,
    SIMPLE_SHIELD,
    SIMPLE_TWO_HANDED_SWORD,
    BONE_MACE,
    SIMPLE_STAFF,

    BOOK_OF_GOBLIN_STORIES,

    APPLE,
    FLOWER_WHITE,
    FLOWER_RED,
    FLOWER_PURPLE,

    COCONUT,
    RED_BERRIES,
    MUSHROOM_1,
    MUSHROOM_2,
    MUSHROOM_3,
    MAGMA_SHROOM,
    MESSAGE_IN_A_BOTTLE,
    NOTE_SCRAP,
    FALLEN_STAR

");