::EnumDef.addToEnum("PlacedItemId", @"

    TREE,
    CHERRY_BLOSSOM_TREE,
    CACTUS,
    TREE_APPLE,
    PALM_TREE,
    PALM_TREE_COCONUTS,
    FLOWER_PURPLE,
    FLOWER_RED,
    FLOWER_WHITE,
    BERRY_BUSH,
    BERRY_BUSH_BERRIES,

    SWAMP_TREE_ONE,
    SWAMP_TREE_TWO,
    SWAMP_TREE_THREE,
    SWAMP_TREE_FOUR,
    SWAMP_BULLRUSH_1,
    SWAMP_BULLRUSH_2,
    SWAMP_GRASS_1,
    SWAMP_GRASS_2,
    SWAMP_LILYPAD,

");