::EnumDef.addToEnum("Screen", @"

    MAIN_MENU_SCREEN,
    HELP_SCREEN,
    SAVE_SELECTION_SCREEN,
    GAMEPLAY_MAIN_MENU_SCREEN,
    EXPLORATION_SCREEN,
    ITEM_INFO_SCREEN,
    INVENTORY_SCREEN,
    VISITED_PLACES_SCREEN,
    DIALOG_SCREEN,
    TEST_SCREEN,
    SAVE_EDIT_SCREEN,
    EXPLORATION_END_SCREEN,
    PLAYER_DEATH_SCREEN,
    WORLD_GENERATION_STATUS_SCREEN,
    NEW_SAVE_VALUES_SCREEN,
    INVENTORY_ITEM_HELPER_SCREEN,
    PAUSE_SCREEN,
    SETTINGS_SCREEN,
    READABLE_CONTENT_SCREEN,

");