::EnumDef.addToEnum("VoxelId", @"
    SAND,
    DIRT,
    SNOW,
    TREES,
    TREES_CHERRY_BLOSSOM,

    DIRT_EXP_FIELD,
    SAND_EXP_FIELD,

    SWAMP_GRASS,
    SWAMP_FOREST_GRASS,

    GEOTHERMAL_DIRT,
    GEOTHERMAL_GRAVEL,
", false);