name: Build and Test

on:
  push:
    branches: 'master'

jobs:
  buildNativeLinux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        buildType: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          sudo apt-get update && sudo apt-get install -y libxaw7-dev libxrandr-dev libxcb-randr0-dev libx11-dev xserver-xorg-dev xorg-dev libx11-xcb1 libxcb-res0-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libgtk-3-dev
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: avBuiltLinux-${{ matrix.buildType }}.tar.gz
          repo: OtherMythos/avBuild
          workflow: linux.yml
      - name: Expand artifact
        run: |
          tar -xvf build.tar.gz
      - name: Setup CMake
        run: |
          mkdir -p native/build
          cd native/build
          git clone https://github.com/OtherMythos/avEngine.git /tmp/avEngine
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildType }} -DENGINE_SOURCE_PATH=/tmp/avEngine -DAV_LIBS_DIR=${{ github.workspace }}/${{ matrix.buildType }} ..
      - name: Build
        run: |
          cd native/build
          cmake --build .
          cp "plugin/libProceduralExplorationGamePlugin.so" "plugin/libProceduralExplorationGamePlugin_${{ matrix.buildType }}-linux-x86_64.so"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libProceduralExplorationGamePlugin_${{ matrix.buildType }}-linux-x86_64.so
          path: "native/build/plugin/libProceduralExplorationGamePlugin_${{ matrix.buildType }}-linux-x86_64.so"

  buildNativeAndroid:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        buildType: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: android
      - name: Download prebuilt Android dependencies
        uses: dawidd6/action-download-artifact@v3
        with:
          name: avBuiltAndroid-${{ matrix.buildType }}.tar.gz
          repo: OtherMythos/avBuild
          workflow: android.yml
      - name: Extract dependencies
        run: |
          mkdir /home/runner/deps
          tar -xvf android-avBuilt-${{ matrix.buildType }}.tar.gz -C /home/runner/deps
          echo "Extracted to deps"
      - name: Set up Java and Android SDK
        uses: android-actions/setup-android@v3
      - name: Download Android NDK r25
        run: |
          curl -L -o ndk.zip https://dl.google.com/android/repository/android-ndk-r25-linux.zip
          unzip -q ndk.zip
          mv android-ndk-r25 ~/ndk
      - name: Setup CMake
        run: |
          git clone https://github.com/OtherMythos/avEngine.git /tmp/avEngine
          cd native
          mkdir build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=${{ matrix.buildType }} \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_NATIVE_API_LEVEL=24 \
            -DCMAKE_TOOLCHAIN_FILE="/home/runner/ndk/build/cmake/android.toolchain.cmake" \
            -DENGINE_SOURCE_PATH="/tmp/avEngine" \
            -DAV_LIBS_DIR="/home/runner/deps/${{ matrix.buildType }}" \
            -DCMAKE_FIND_ROOT_PATH="/home/runner/deps/${{ matrix.buildType }}" \
            -DCMAKE_FIND_DEBUG_MODE=OFF \
            -DPLATFORM=android \
            ..
      - name: Build
        run: |
          cd native/build
          cmake --build .
          cp plugin/libProceduralExplorationGamePlugin_static.a /home/runner/libProceduralExplorationGamePlugin_android_static_${{ matrix.buildType }}.a
          cp core/libProceduralExplorationGameNativeCore.a /home/runner/libProceduralExplorationGameNativeCore_android_static_${{ matrix.buildType }}.a
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libProceduralExplorationGamePlugin_android_static_${{ matrix.buildType }}.a
          path: "/home/runner/libProceduralExplorationGamePlugin_android_static_${{ matrix.buildType }}.a"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libProceduralExplorationGameNativeCore_android_static_${{ matrix.buildType }}.a
          path: "/home/runner/libProceduralExplorationGameNativeCore_android_static_${{ matrix.buildType }}.a"

  buildNativeWindows:
    runs-on: windows-2019
    strategy:
      matrix:
        buildType: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: avBuiltWindows-${{ matrix.buildType }}.zip
          repo: OtherMythos/avBuild
          workflow: windows.yml
      - name: Download avCore artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: avCore-${{ matrix.buildType }}.lib
          repo: OtherMythos/avEngine
          workflow: buildWindows.yml
      - name: Expand artifact
        run: |
          Expand-Archive avBuilt-windows-${{ matrix.buildType }}.zip .
      - name: Clone dependencies
        run: |
          git clone https://github.com/OtherMythos/avEngine.git D:/avEngine
          cd D:\avEngine
          mkdir build
          cd build
          mkdir ${{ matrix.buildType }}
          cd ${{ matrix.buildType }}
          cp ${{ github.workspace }}/avCore.lib avCore.lib
      - name: Setup CMake
        run: |
          cd native
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildType }} -DENGINE_SOURCE_PATH='D:\avEngine' -DAV_LIBS_DIR=${{ github.workspace }}/avBuilt/${{ matrix.buildType }} ..
      - name: Build
        run: |
          cd native/build
          cmake --build . --config ${{ matrix.buildType }}
          cp "plugin/${{ matrix.buildType }}/ProceduralExplorationGamePlugin.dll" "plugin/${{ matrix.buildType }}/ProceduralExplorationGamePlugin_${{ matrix.buildType }}-windows-x86_64.dll"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ProceduralExplorationGamePlugin_${{ matrix.buildType }}-windows-x86_64.dll
          path: "native/build/plugin/${{ matrix.buildType }}/ProceduralExplorationGamePlugin_${{ matrix.buildType }}-windows-x86_64.dll"

  build:
    needs: ['buildNativeLinux', 'buildNativeWindows', 'buildNativeAndroid']
    runs-on: ubuntu-24.04

    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup plugins
        run: |
          mkdir plugins
      - name: Download Windows Debug native plugin
        uses: actions/download-artifact@v4
        with:
          name: ProceduralExplorationGamePlugin_Debug-windows-x86_64.dll
          path: plugins/
      - name: Download Windows Release native plugin
        uses: actions/download-artifact@v4
        with:
          name: ProceduralExplorationGamePlugin_Release-windows-x86_64.dll
          path: plugins/
      - name: Download Linux Debug native plugin
        uses: actions/download-artifact@v4
        with:
          name: libProceduralExplorationGamePlugin_Debug-linux-x86_64.so
          path: plugins/
      - name: Download Linux Release native plugin
        uses: actions/download-artifact@v4
        with:
          name: libProceduralExplorationGamePlugin_Release-linux-x86_64.so
          path: plugins/
      - name: Download Android Debug native plugin
        uses: actions/download-artifact@v4
        with:
          name: libProceduralExplorationGamePlugin_android_static_Debug.a
          path: plugins/
      - name: Download Android Release native plugin
        uses: actions/download-artifact@v4
        with:
          name: libProceduralExplorationGamePlugin_android_static_Release.a
          path: plugins/
      - name: Download Android Debug native core
        uses: actions/download-artifact@v4
        with:
          name: libProceduralExplorationGameNativeCore_android_static_Debug.a
          path: plugins/
      - name: Download Android Release native core
        uses: actions/download-artifact@v4
        with:
          name: libProceduralExplorationGameNativeCore_android_static_Release.a
          path: plugins/
      - name: Build
        run: |
          mkdir /tmp/distribution
          cp -r avSetup.cfg /tmp/distribution
          cp -r OgreResources.cfg /tmp/distribution
          cp -r src /tmp/distribution
          cp -r plugins /tmp/distribution
          echo >> /tmp/distribution/src/Versions.h.nut
          echo "const GIT_HASH = \"${{ steps.vars.outputs.sha_short }}\"" >> /tmp/distribution/src/Versions.h.nut
          ./resBuild.sh --clean
          cp -r build /tmp/distribution
      - name: Copy plugin includes
        run: |
          mkdir -p /tmp/distribution/plugins/include/native/plugin/src/
          cp native/plugin/src/ProceduralExplorationGameCorePlugin.h /tmp/distribution/plugins/include/native/plugin/src/ProceduralExplorationGameCorePlugin.h
          cp CMakeLists.txt StaticPlugins.h /tmp/distribution
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distribution-${{ steps.vars.outputs.sha_short }}
          path: /tmp/distribution

  buildWindows:
    runs-on: windows-2019
    needs: build
    strategy:
      matrix:
        buildType: [Debug, Release]

    steps:
      - name: Clone Build
        uses: dawidd6/action-download-artifact@v3
        with:
          name: avEngineWindows-${{ matrix.buildType }}.zip
          repo: OtherMythos/avEngine
          workflow: buildWindows.yml
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: distribution-${{ needs.build.outputs.sha_short }}
      - name: Remove unecessary files
        run: |
          cp plugins\ProceduralExplorationGamePlugin_${{ matrix.buildType }}-windows-x86_64.dll ${{ github.workspace }}\
          rm plugins\ -r -Force
          mkdir plugins\
          cp ${{ github.workspace }}\ProceduralExplorationGamePlugin_${{ matrix.buildType }}-windows-x86_64.dll plugins\
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: buildWindows-${{ matrix.buildType }}-${{ needs.build.outputs.sha_short }}
          path: ${{ github.workspace }}

  buildLinux:
    runs-on: ubuntu-24.04
    needs: build
    strategy:
      matrix:
        buildType: [Debug, Release]

    steps:
      - name: Clone Build
        uses: dawidd6/action-download-artifact@v3
        with:
          name: av-x86_64-${{ matrix.buildType }}.AppImage
          repo: OtherMythos/avEngine
          workflow: buildLinux.yml
      - name: Extract appimage
        run: |
          chmod +x ./av-x86_64.AppImage
          ./av-x86_64.AppImage --appimage-extract
          ls
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: distribution-${{ needs.build.outputs.sha_short }}
          path: squashfs-root/usr/bin
      - name: Reduce distribution
        run: |
          rm squashfs-root/usr/bin/plugins/*.dll
          if [ "${{ matrix.buildType }}" == "Debug" ]; then
            rm squashfs-root/usr/bin/plugins/*Release*
          else
            rm squashfs-root/usr/bin/plugins/*Debug*
          fi
      - name: Setup appimage
        run: |
          #cd /tmp
          chmod -R 777 squashfs-root/usr/bin/build
          wget -O /usr/local/bin/appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x /usr/local/bin/appimagetool
          ls
          sudo apt update
          sudo apt install fuse libfuse2
          #./appimagetool-x86_64.AppImage --appimage-extract
          #cd squashfs-root/usr/bin
          #ls
          #cd /tmp
          appimagetool squashfs-root
          rm -rf squashfs-root
          mv av-x86_64.AppImage buildLinux-${{ matrix.buildType }}-${{ needs.build.outputs.sha_short }}.AppImage
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: buildLinux-${{ matrix.buildType }}-${{ needs.build.outputs.sha_short }}.AppImage
          path: ${{ github.workspace }}/buildLinux-${{ matrix.buildType }}-${{ needs.build.outputs.sha_short }}.AppImage

  buildAndroid:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        buildType: [Debug, Release]

    steps:
      - name: Set lowercase build type
        run: echo "BUILD_TYPE_LOWER=$(echo '${{ matrix.buildType }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Checkout avEngine-android
        uses: actions/checkout@v4
        with:
          repository: OtherMythos/avEngine-android
          path: avEngine-android

      - name: Replace avEngine submodule with this version
        run: |
          rm -rf avEngine-android/app/src/main/avEngine

      - name: Checkout engine
        uses: actions/checkout@v4
        with:
          path: avEngine-android/app/src/main/avEngine
          repository: 'OtherMythos/avEngine'

      - name: Download prebuilt Android dependencies
        uses: dawidd6/action-download-artifact@v3
        with:
          name: avBuiltAndroid-${{ matrix.buildType }}.tar.gz
          repo: OtherMythos/avBuild
          workflow: android.yml

      - name: Extract dependencies
        run: |
          mkdir deps
          tar -xvf android-avBuilt-${{ matrix.buildType }}.tar.gz -C deps
          echo "Extracted to deps"

      - name: Set up Java and Android SDK
        uses: android-actions/setup-android@v3

      - name: Download Android NDK r25
        run: |
          curl -L -o ndk.zip https://dl.google.com/android/repository/android-ndk-r25-linux.zip
          unzip -q ndk.zip
          mv android-ndk-r25 ~/ndk

      - name: Set local.properties
        run: echo "ndk.dir=/home/runner/ndk" >> avEngine-android/local.properties

      - name: Set JAVA_HOME explicitly (needed for some gradle builds)
        run: echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: distribution-${{ needs.build.outputs.sha_short }}
      - name: Remove unecessary files
        run: |
          cp plugins/libProceduralExplorationGamePlugin_android_static_${{ matrix.buildType }}.a ${{ github.workspace }}/
          rm -rf plugins

      - name: Run setup.py
        working-directory: avEngine-android
        run: |
          python3 setup.py ${{ github.workspace }}/deps/${{ matrix.buildType }}/ --extra-args="-DUSE_STATIC_PLUGINS=True" --extra-args="-DAV_PROJECT_DIR=${{ github.workspace }}"

      - name: Build APK
        working-directory: avEngine-android
        run: ./gradlew assemble${{ matrix.buildType }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: avEngine-android-${{ matrix.buildType }}.apk
          path: |
            avEngine-android/app/build/outputs/apk/${{env.BUILD_TYPE_LOWER}}/app-${{env.BUILD_TYPE_LOWER}}.apk
            avEngine-android/app/build/outputs/apk/${{env.BUILD_TYPE_LOWER}}/app-${{env.BUILD_TYPE_LOWER}}-unsigned.apk

  runUnitTests:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      checks: write
      pull-requests: write
    strategy:
      matrix:
        buildType: [Debug, Release]
        rendersystem: [OpenGL, Vulkan]

    steps:
      - name: Setup OpenGL
        run: |
          sudo apt update
          sudo apt install mesa-utils xvfb fuse libfuse2
      - name: Clone Build
        uses: dawidd6/action-download-artifact@v3
        with:
          name: av-x86_64-${{ matrix.buildType }}.AppImage
          repo: OtherMythos/avEngine
          workflow: buildLinux.yml
      - name: Checkout Game Code
        uses: actions/checkout@v4
        with:
          path: ./checkout
      - name: Checkout avTools
        uses: actions/checkout@v4
        with:
          path: ./avTools
          repository: OtherMythos/avTools
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: distribution-${{ needs.build.outputs.sha_short }}
      - name: Run tests
        run: |
          cp -r checkout/test .
          chmod +x ./av-x86_64.AppImage
          mkdir /tmp/testLogs
          xvfb-run python avTools/testRunner/testRunner.py -l /tmp/testLogs -e ./av-x86_64.AppImage -p test/avTests.cfg -o /home/runner/work/results.xml --flags="--rendersystem ${{ matrix.rendersystem }}"
      - name: Check results
        if: always()
        run: |
          pwd
          cp /home/runner/work/results.xml .
          ls
          cat results.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            results.xml
      - name: Upload Logs Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testLogs-${{ matrix.buildType }}-${{ matrix.rendersystem }}
          path: /tmp/testLogs